
const $=id=>document.getElementById(id);
const SELLERS={ana:{label:"Ana",phone:"5581996763982"},dayane:{label:"Dayane",phone:"5581983383002"}};
let view="themes", themes=[], products=[], items=[], selectedTheme=null, selectedProduct=null, cart=[], seller=null, prev=null, favs=new Set(), showFavs=false, searchTimer=null;
const STORAGE="armazemHubCartV2";
const FAV_STORAGE="armazemHubFavsV2";
const phrases=["Buscando artes lindas para você...","Separando os temas com carinho...","Organizando as opções da sua festa...","Preparando uma seleção cheia de possibilidades...","Só mais um instante, estamos deixando tudo prontinho...","Carregando as artes da Armazém para você escolher com calma..."];
let phraseIndex=0, phraseTimer=null;
function esc(v){return String(v??"").replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[m]))}
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function label(key){return ({"50x50":"Bolinhas 50x50","painel-150":"Painel 150x150","cenario":"Cenário","lateral":"Lateral","sacolinha":"Sacolinha de Festa","cilindros":"Cilindros","romano":"Romano","kit-romano":"Kit + Romano","kit-painel-cilindros":"Kit Painel + Cilindros","produto":"Produto"})[key]||key}
function loading(sub="Estamos preparando tudo para você."){$("content").innerHTML=`<div class="loading"><div><div class="loaderDot"></div><p class="loadPhrase" id="loadPhrase">${phrases[phraseIndex%phrases.length]}</p><div class="loadSub">${esc(sub)}</div></div></div>`;clearInterval(phraseTimer);phraseTimer=setInterval(()=>{phraseIndex++;const el=$("loadPhrase");if(el){el.style.opacity=0;setTimeout(()=>{if($("loadPhrase")){el.textContent=phrases[phraseIndex%phrases.length];el.style.opacity=1}},220)}},2200)}
function stopLoading(){clearInterval(phraseTimer)}
function api(params){const q=new URLSearchParams(params);return fetch(`/api/drive?${q.toString()}`,{cache:"no-store"}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||"Não conseguimos carregar as artes agora.");return d})}
const DEMO_PRODUCTS=[
  {id:"demo-prod-lateral",name:"Lateral",productName:"Lateral",product:"lateral",rawName:"Lateral"},
  {id:"demo-prod-50",name:"50x50",productName:"Bolinhas 50x50",product:"50x50",rawName:"50x50"},
  {id:"demo-prod-150",name:"Painel 150x150",productName:"Painel 150x150",product:"painel-150",rawName:"Painel 150x150"},
  {id:"demo-prod-cil",name:"Cilindros",productName:"Cilindros",product:"cilindros",rawName:"Cilindros"},
  {id:"demo-prod-kit",name:"Kit + Romano",productName:"Kit + Romano",product:"kit-romano",rawName:"Kit + Romano"},
  {id:"demo-prod-rom",name:"Romano",productName:"Romano",product:"romano",rawName:"Romano"},
  {id:"demo-prod-sac",name:"Sacolinha de Festa",productName:"Sacolinha de Festa",product:"sacolinha",rawName:"Sacolinha"}
];
function useDemoThemes(){themes=["101 Dálmatas","Fazendinha","Princesa","Safari","Jardim Encantado","Fundo do Mar"].map((name,i)=>({id:`demo-theme-${i+1}`,name}));showThemes();toast("Modo demonstração: você já pode testar temas, produtos e carrinho.")}
function demoItemsFor(product,themeObj=selectedTheme){const t=themeObj?.name||"Tema";const tid=themeObj?.id||"demo-theme";const base=[220,195,188,177,164,163,142,130,118,101];return base.map((n,idx)=>({id:`${tid}-${product.id}-${n}`,code:String(n),sortId:n,theme:t,themeId:tid,product:product.product||"produto",productName:product.productName||product.name||label(product.product),productFolderId:product.id,image:`https://placehold.co/900x900/${["fff0f6","eefdff","fff7d1","f8f5f3","eefbf6"][idx%5]}/222124?text=%23${n}`}))}
function demoSearchByCode(q){const query=normalize(q).replace(/[^0-9]/g,"");const demoThemes=(themes&&themes.length?themes:["101 Dálmatas","Fazendinha","Princesa","Safari","Jardim Encantado","Fundo do Mar"].map((name,i)=>({id:`demo-theme-${i+1}`,name})));let out=[];demoThemes.forEach(t=>DEMO_PRODUCTS.forEach(p=>out.push(...demoItemsFor(p,t))));return out.filter(i=>String(i.code).includes(query)).sort((a,b)=>(b.sortId||0)-(a.sortId||0)).slice(0,60)}
async function globalCodeSearch(q){view="search";selectedProduct=null;showFavs=false;updateHead("Busca por código",`Procurando a arte #${q}. Se ela aparecer, você pode adicionar direto ao pedido.`,"buscando");loading("Procurando essa arte para você...");try{const d=await api({mode:"search",code:q});items=d.items||[];if(!items.length&&String(q).match(/\d/))items=demoSearchByCode(q);renderItems()}catch(e){items=demoSearchByCode(q);renderItems();if(items.length)toast("Mostrando opções de demonstração para testar a busca.")}}
function errorScreen(message){stopLoading();$("content").innerHTML=`<div class="errorBox"><h3>Não conseguimos carregar as artes agora</h3><p>As artes não carregaram neste momento. Você pode tentar novamente ou chamar uma vendedora para receber ajuda com carinho.</p><div class="errorActions"><button id="retryLoad">Tentar novamente</button><a href="https://wa.me/${SELLERS.ana.phone}" target="_blank">Falar com Ana</a><a href="https://wa.me/${SELLERS.dayane.phone}" target="_blank">Falar com Dayane</a></div></div>`;$("retryLoad").onclick=()=> view==="themes"?loadThemes():view==="products"?loadProducts(selectedTheme):loadItems(selectedProduct)}
function save(){localStorage.setItem(STORAGE,JSON.stringify({cart,seller}));localStorage.setItem(FAV_STORAGE,JSON.stringify([...favs]))}
function restore(){try{const f=JSON.parse(localStorage.getItem(FAV_STORAGE)||"[]");favs=new Set(f)}catch(e){}try{const fromUrl=new URLSearchParams(location.search).get("pedido");if(fromUrl){const d=JSON.parse(decodeURIComponent(escape(atob(fromUrl))));cart=d.cart||[];seller=null;save();history.replaceState(null,"",location.pathname);toast("Pedido carregado pelo link compartilhado. Escolha a vendedora para enviar.");return}const d=JSON.parse(localStorage.getItem(STORAGE)||"{}");cart=Array.isArray(d.cart)?d.cart:[];seller=null}catch(e){cart=[];seller=null}}
function sharePayload(){return btoa(unescape(encodeURIComponent(JSON.stringify({cart,seller}))))}
function copyShare(){const url=`${location.origin}${location.pathname}?pedido=${sharePayload()}`;navigator.clipboard?.writeText(url).then(()=>toast("Link do pedido copiado."),()=>toast("Não consegui copiar o link agora."))}
function updateHead(title,caption,count){$("viewTitle").textContent=title;$("viewCaption").textContent=caption;$("count").textContent=count;$("search").hidden=false;$("search").placeholder=(view==="items"||view==="search")?"Buscar pelo código da arte...":"Digite o código da arte ou busque por tema/peça...";$("favToggle").hidden=view!=="items";$("addFavs").hidden=view!=="items";$("favToggle").textContent=showFavs?"Ver todas":"Ver favoritas";renderCrumbs()}
function renderCrumbs(){const b=$("breadcrumbs");let html="";if(view!=="themes")html+=`<button class="backBtn" data-back="themes">Temas</button>`;if(selectedTheme)html+=`<span class="crumb">${esc(selectedTheme.name)}</span>`;if(view==="items")html+=`<button class="backBtn" data-back="products">Produtos</button><span class="crumb">${esc(selectedProduct.productName||selectedProduct.name)}</span>`;b.innerHTML=html;b.querySelectorAll("[data-back]").forEach(x=>x.onclick=()=>x.dataset.back==="themes"?showThemes():showProducts())}
async function loadThemes(){view="themes";selectedTheme=null;selectedProduct=null;$("search").value="";updateHead("Escolha um tema","Escolha o tema da sua festa ou digite o código de uma arte para procurar direto.","carregando");loading("Buscando artes lindas para você...");try{const d=await api({mode:"themes"});themes=d.folders||[];showThemes()}catch(e){useDemoThemes()}}
function filteredThemes(){const q=normalize($("search").value);return q?themes.filter(t=>normalize(t.name).includes(q)):themes}
function showThemes(){stopLoading();view="themes";selectedTheme=null;selectedProduct=null;const list=filteredThemes();updateHead("Escolha um tema","Escolha o tema que mais combina com a sua festa. Depois você vê os produtos disponíveis e escolhe suas artes com calma.",`${list.length} tema(s)`);$("content").innerHTML=list.length?`<div class="themeGrid">${list.map(t=>`<button class="themeCard" data-theme="${esc(t.id)}"><b>${esc(t.name)}</b><span>Toque para ver as opções desse tema.</span></button>`).join("")}</div>`:`<div class="empty"><div><b>Nenhum tema encontrado</b><span>Tente buscar por outro nome ou apague a busca para ver todos os temas.</span></div></div>`;document.querySelectorAll("[data-theme]").forEach(btn=>btn.onclick=()=>{const t=themes.find(x=>x.id===btn.dataset.theme);loadProducts(t)})}
async function loadProducts(theme){selectedTheme=theme;view="products";selectedProduct=null;$("search").value="";updateHead("Escolha o produto",`Agora escolha qual peça você quer ver no tema ${theme.name}.`,"carregando");loading("Separando as peças desse tema com carinho...");try{const d=await api({mode:"products",folderId:theme.id,theme:theme.name});products=d.folders||[];showProducts()}catch(e){if(String(theme.id||"").startsWith("demo-")){products=DEMO_PRODUCTS;showProducts()}else errorScreen(e.message)}}
function filteredProducts(){const q=normalize($("search").value);return q?products.filter(p=>normalize(`${p.productName||p.name} ${p.rawName||""}`).includes(q)):products}
function showProducts(){stopLoading();view="products";const list=filteredProducts();updateHead("Escolha o produto",`Agora escolha qual peça você quer personalizar no tema ${selectedTheme.name}.`,`${list.length} produto(s)`);$("content").innerHTML=list.length?`<div class="productGrid">${list.map(p=>`<button class="productCard" data-product="${esc(p.id)}"><b>${esc(p.productName||p.name)}</b><span>Escolha esse produto e veja as artes disponíveis.</span></button>`).join("")}</div>`:`<div class="empty"><div><b>Nenhum produto encontrado</b><span>Tente buscar por outro produto ou volte para escolher outro tema.</span></div></div>`;document.querySelectorAll("[data-product]").forEach(btn=>btn.onclick=()=>{const p=products.find(x=>x.id===btn.dataset.product);loadItems(p)})}
async function loadItems(product){selectedProduct=product;view="items";showFavs=false;$("search").value="";updateHead("Escolha suas artes",`Toque na arte para ver melhor. Quando gostar, adicione ao seu pedido; o desconto de 10% entra automaticamente.`,"carregando");loading("Preparando as artes para você escolher com calma...");try{const d=await api({mode:"items",folderId:product.id,theme:selectedTheme.name,product:product.rawName||product.name||product.productName});items=d.items||[];renderItems()}catch(e){if(String(product.id||"").startsWith("demo-")){items=demoItemsFor(product);renderItems()}else errorScreen(e.message)}}
function filteredItems(){const q=normalize($("search").value);let list=items;if(showFavs)list=list.filter(i=>favs.has(i.id));if(q)list=list.filter(i=>normalize(`${i.code} ${i.theme} ${i.productName}`).includes(q));return list}
function normalize(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function entry(id){return cart.find(c=>c.id===id)}function cartQty(){return cart.reduce((s,c)=>s+c.qty,0)}
function renderItems(){stopLoading();const list=filteredItems();const isSearch=view==="search";updateHead(isSearch?"Resultado da busca":(showFavs?"Suas favoritas":"Escolha suas artes"),isSearch?"Encontramos as artes com esse código. Confira a imagem e adicione a que você quiser ao pedido.":(showFavs?"Aqui estão as artes que você marcou para comparar. Você pode adicionar uma por uma ou todas ao carrinho.":"Toque na imagem para ampliar. Quando gostar, adicione ao pedido ou marque como favorita."),`${list.length} arte(s)`);$("content").innerHTML=list.length?`<div class="grid">${list.map(i=>{const e=entry(i.id);const fav=favs.has(i.id);return `<article class="card ${e?"sel":""}" data-card="${esc(i.id)}"><div class="thumbWrap" data-preview="${esc(i.id)}"><img class="thumb" loading="lazy" src="${esc(i.image)}" alt="Arte código ${esc(i.code)}"><span class="code">#${esc(i.code)}</span>${e?`<span class="badge">Selecionada ${e.qty}x</span>`:`<span class="badge">Toque para ver melhor</span>`}<button class="favBtn ${fav?"active":""}" data-fav="${esc(i.id)}" aria-label="Favoritar">${fav?"♥":"♡"}</button></div><div class="info"><p class="codeTitle">Código #${esc(i.code)}</p><div class="miniRow"><span class="mini">${esc(i.theme)}</span><span class="mini">${esc(i.productName)}</span></div>${e?`<span class="inCartNote">No carrinho: ${e.qty} unidade(s)</span><div class="cardActions two"><button class="selBtn" data-select="${esc(i.id)}">Adicionar 1 unidade</button><button class="removeBtn" data-remove="${esc(i.id)}">Tirar 1 unidade</button></div>`:`<div class="cardActions"><button class="selBtn" data-select="${esc(i.id)}">Adicionar arte</button></div>`}</div></article>`}).join("")}</div>`:`<div class="empty"><div><b>Nenhuma arte encontrada por aqui</b><span>Tente buscar por outro código ou volte para escolher outra peça.</span></div></div>`;document.querySelectorAll("[data-select]").forEach(b=>b.onclick=()=>addItem(b.dataset.select));document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>changeQty(b.dataset.remove,-1));document.querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>openPreview(b.dataset.preview));document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)})}
function toggleFav(id){if(favs.has(id)){favs.delete(id);toast("Removida das favoritas.")}else{favs.add(id);toast("Guardada nas favoritas.")}save();renderItems()}
function addFavorites(){const fs=items.filter(i=>favs.has(i.id));if(!fs.length){toast("Você ainda não marcou favoritas neste produto.");return}fs.forEach(i=>{let e=entry(i.id);if(e)e.qty+=1;else cart.push({...i,qty:1})});save();renderItems();renderCart();toast("Favoritas adicionadas ao pedido.")}
function addItem(id){const it=items.find(x=>x.id===id)||cart.find(x=>x.id===id);if(!it)return;let e=entry(id);if(e)e.qty+=1;else cart.push({...it,qty:1});save();toast(e?"Mais 1 unidade adicionada.":"Arte adicionada ao pedido.");if(view==="items"||view==="search")renderItems();renderCart()}
function changeQty(id,delta){const e=entry(id);if(!e)return;e.qty+=delta;if(e.qty<=0)cart=cart.filter(c=>c.id!==id);save();if(view==="items"||view==="search")renderItems();renderCart()}
function price(product,qty){if(!qty)return 0;if(product==="50x50")return qty>=6?58.90+Math.max(0,qty-6)*9.90:qty*9.90;if(product==="painel-150"||product==="cenario"||product==="lateral")return qty*59.90;if(product==="kit-romano")return qty*210;if(product==="cilindros")return qty*99;if(product==="romano")return qty*78;if(product==="kit-painel-cilindros")return qty*158.90;if(product==="sacolinha")return 0;return 0}
function groups(){const m=new Map();cart.forEach(i=>{const key=i.product||"produto";if(!m.has(key))m.set(key,{product:key,label:i.productName||label(key),items:[],qty:0});m.get(key).items.push(i);m.get(key).qty+=i.qty});return [...m.values()].map(g=>({...g,items:g.items.sort((a,b)=>(b.sortId||0)-(a.sortId||0)),subtotal:price(g.product,g.qty)}))}
function gross(){return groups().reduce((s,g)=>s+g.subtotal,0)}function discount(){return gross()*0.10}function total(){return Math.max(0,gross()-discount())}
function rule50(){const q=cart.filter(i=>i.product==="50x50").reduce((s,i)=>s+i.qty,0);if(q===0)return null;if(q<6)return{type:"bad",title:"Bolinhas 50x50",msg:`Você selecionou ${q} unidade(s). Faltam ${6-q} para fechar o mínimo de 6.`};if(q>6&&q%2!==0)return{type:"warn",title:"Bolinhas 50x50",msg:`Você selecionou ${q} unidade(s). Depois de 6, precisa fechar em pares: adicione mais 1 para completar ${q+1}.`};return{type:"ok",title:"Bolinhas 50x50",msg:q===6?"Pedido mínimo fechado. Agora, se quiser aumentar, adicione sempre de 2 em 2: 8, 10, 12...":`Tudo certo: ${q} unidade(s), quantidade par fechada.`}}
function cartRule(){const r=rule50();if(cartQty()===0)return{ok:false,msg:"Seu pedido ainda está vazio. Escolha o tema da festa e adicione as artes que mais gostar. O desconto de 10% entra automaticamente."};if(r&&r.type!=="ok")return{ok:false,msg:r.msg};if(!seller)return{ok:false,msg:"Escolha Ana ou Dayane para enviarmos sua seleção para a vendedora certa."};return{ok:true,msg:"Perfeito. Sua seleção está pronta para enviar com 10% de desconto por aqui."}}
function itemLine(i){return `#${i.code}${i.qty>1?` (${i.qty} un.)`:""}`}
function cartMarkup(){const r=cartRule(),rf=rule50(),can=cartQty()&&r.ok,gs=groups();return `<div class="cartTitle"><h2>Seu orçamento</h2><span class="pill">${cartQty()} item(ns)</span></div><div class="seller"><label>Escolha sua vendedora</label><p class="sellerHint">Selecione para quem você quer enviar sua seleção no WhatsApp.</p><div class="sellerOpts"><button class="sellerBtn ${seller==="ana"?"active":""}" data-seller="ana">Ana</button><button class="sellerBtn ${seller==="dayane"?"active":""}" data-seller="dayane">Dayane</button></div></div>${cartQty()?`<div class="discountCard"><span>10% OFF por aqui</span><strong>Você economiza ${money(discount())}</strong><small>O desconto já entra automaticamente no total antes de enviar para a vendedora. Quanto mais você escolhe por aqui, mais fácil fica finalizar seu pedido.</small></div>`:""}${rf?`<div class="ruleCard ${rf.type==="ok"?"":rf.type}"><b>${rf.title}</b><br>${rf.msg}</div>`:""}<div class="cartList">${gs.length?gs.map(g=>`<section class="group"><div class="groupHead"><b>${esc(g.label)} · ${g.qty} unidade(s)</b><span class="subtotal">${money(g.subtotal)}</span></div><div class="codes"><strong>Tema(s):</strong> ${esc([...new Set(g.items.map(i=>i.theme))].join(", "))}</div>${g.items.map(i=>`<div class="cartItem" data-locate="${esc(i.id)}"><img class="cartThumb" src="${esc(i.image)}" alt="Arte #${esc(i.code)}"><div class="cartInfo"><b>Código #${esc(i.code)}</b><span>${esc(i.theme)} · ${esc(i.productName)}</span><div class="qtyRow"><button class="qtyBtn" data-minus="${esc(i.id)}">−</button><span class="qtyCount">${i.qty} un.</span><button class="qtyBtn" data-plus="${esc(i.id)}">+</button></div><div class="findHint">Toque no item para encontrar essa arte.</div></div></div>`).join("")}</section>`).join(""):`<div class="emptyCart"><b>Seu pedido ainda está vazio</b>Escolha um tema que combine com sua festa e adicione as artes que mais gostar. O desconto de 10% será aplicado automaticamente no final.</div>`}</div><div class="ruleCard ${r.ok?"":"warn"}">${esc(r.msg)}</div><div class="totalBox"><div class="totalLine"><span>Subtotal</span><strong>${money(gross())}</strong></div><div class="totalLine"><span>Desconto por aqui 10%</span><strong>- ${money(discount())}</strong></div><div class="total"><span>Total com desconto</span><strong>${money(total())}</strong></div><div class="actions"><a class="wa ${can?"":"disabled"}" href="${can?esc(waUrl()):"#"}" target="_blank" rel="noopener">Enviar pedido com 10% OFF</a><button class="clear" data-clear ${cartQty()?"":"disabled"}>Limpar carrinho</button></div></div>`}
function renderCart(){$("cartDesk").innerHTML=cartMarkup();$("cartMob").innerHTML=cartMarkup();[$("cartDesk"),$("cartMob")].forEach(p=>{p.querySelectorAll("[data-seller]").forEach(b=>b.onclick=()=>{seller=b.dataset.seller;save();renderCart()});p.querySelectorAll("[data-minus]").forEach(b=>b.onclick=e=>{e.stopPropagation();changeQty(b.dataset.minus,-1)});p.querySelectorAll("[data-plus]").forEach(b=>b.onclick=e=>{e.stopPropagation();changeQty(b.dataset.plus,1)});p.querySelectorAll("[data-locate]").forEach(b=>b.onclick=()=>locateItem(b.dataset.locate));const cl=p.querySelector("[data-clear]");if(cl)cl.onclick=()=>{cart=[];save();if(view==="items"||view==="search")renderItems();renderCart();toast("Carrinho limpo.")}});$("barItems").textContent=`${cartQty()} item(ns)`;$("barTotal").textContent=money(total())}
async function locateItem(id){const it=entry(id);if(!it)return;try{$("drawerBg").classList.remove("show");$("drawer").classList.remove("show");if(!selectedTheme||selectedTheme.id!==it.themeId){selectedTheme={id:it.themeId,name:it.theme};view="products";loading("Abrindo o tema da arte.");const d=await api({mode:"products",folderId:it.themeId,theme:it.theme});products=d.folders||[]}selectedProduct=products.find(p=>p.id===it.productFolderId)||{id:it.productFolderId,product:it.product,productName:it.productName,name:it.productName};view="items";loading("Encontrando sua arte.");const d=await api({mode:"items",folderId:selectedProduct.id,theme:it.theme,product:selectedProduct.rawName||selectedProduct.name||selectedProduct.productName});items=d.items||[];renderItems();setTimeout(()=>{const el=document.querySelector(`[data-card="${CSS.escape(id)}"]`);if(el){el.scrollIntoView({behavior:"smooth",block:"center"});el.classList.add("located");setTimeout(()=>el.classList.remove("located"),1900)}},80)}catch(e){toast("Não consegui voltar para essa arte agora.")}}
function waMsg(){const s=SELLERS[seller]||SELLERS.ana;const lines=[`Oi, ${s.label}! Separei minhas artes por aqui, na página da Armazém.`,"",`Escolhendo por aqui, meu pedido ganha 10% de desconto. O total abaixo já está com o desconto aplicado.`,"",`Minha seleção:`];groups().forEach(g=>{lines.push("",g.label,`Tema(s): ${[...new Set(g.items.map(i=>i.theme))].join(", ")}`,`Códigos: ${g.items.map(itemLine).join(", ")}`,`Quantidade total: ${g.qty}`,`Subtotal: ${money(g.subtotal)}`)});lines.push("",`Subtotal antes do desconto: ${money(gross())}`,`Desconto por aqui 10%: - ${money(discount())}`,`Total final com desconto: ${money(total())}`,"",`Pode confirmar as artes e me ajudar a finalizar, por favor?`);return lines.join("\n")}
function waUrl(){if(!seller)return"#";return`https://wa.me/${SELLERS[seller].phone}?text=${encodeURIComponent(waMsg())}`}
function openPreview(id){const i=items.find(x=>x.id===id)||cart.find(x=>x.id===id);if(!i)return;prev=i;$("prevImg").src=i.image;$("prevCode").textContent="#"+i.code;$("prevTitle").textContent="Código #"+i.code;$("prevMeta").innerHTML=`<span class="mini">${esc(i.theme)}</span><span class="mini">${esc(i.productName)}</span>`;$("prevSelect").textContent=entry(i.id)?"Adicionar 1 unidade":"Adicionar arte";$("prevFav").textContent=favs.has(i.id)?"Remover favorita":"Favoritar";$("modalBg").classList.add("show");$("modal").classList.add("show")}
function closePreview(){$("modalBg").classList.remove("show");$("modal").classList.remove("show");prev=null}
function toast(msg){const e=$("toast");e.textContent=msg;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1900)}
$("search").oninput=()=>{clearTimeout(searchTimer);const q=$("search").value.trim();const code=q.replace(/\D/g,"");if((view==="themes"||view==="products"||view==="search")&&code.length>=2){searchTimer=setTimeout(()=>globalCodeSearch(code),360);return}if(view==="search"&&q.length===0){loadThemes();return}if(view==="themes")showThemes();else if(view==="products")showProducts();else if(view==="items")renderItems()};$("openCart").onclick=()=>{$("drawerBg").classList.add("show");$("drawer").classList.add("show")};$("drawerBg").onclick=()=>{$("drawerBg").classList.remove("show");$("drawer").classList.remove("show")};$("modalBg").onclick=closePreview;$("prevClose").onclick=closePreview;$("prevSelect").onclick=()=>{if(prev)addItem(prev.id);closePreview()};$("prevFav").onclick=()=>{if(prev)toggleFav(prev.id);closePreview()};$("favToggle").onclick=()=>{showFavs=!showFavs;renderItems()};$("addFavs").onclick=addFavorites;
restore();renderCart();loadThemes();
