import { loadConfig, getActiveDrive, getBolinhas } from "./_config.js";
import { applyFolderRule, cleanLabel, displayTheme, isBlockedArt, isHiddenTheme, sortFolders, norm as normalizeText } from "./_catalog_rules.js";
const DEFAULT_ROOT_FOLDER_ID="193kW8g7EsmrNwlGE3ugbC3qzOcDEwUae";
const DRIVE_API="https://www.googleapis.com/drive/v3/files";
const FOLDER_MIME="application/vnd.google-apps.folder";

export async function onRequestGet(context){
 try{
  const apiKey=context.env.GOOGLE_API_KEY||context.env.GOOGLE_DRIVE_API_KEY||context.env.DRIVE_API_KEY;
  if(!apiKey)return json({ok:false,error:"GOOGLE_API_KEY_NAO_CONFIGURADA"},500);
  const {config}=await loadConfig(context.env); const drive=getActiveDrive(config,"bolinhas"); const bolinhas=getBolinhas(config);
  const rootFolderId=sanitizeId(drive&&drive.folderId)||DEFAULT_ROOT_FOLDER_ID;
  const url=new URL(context.request.url); const mode=String(url.searchParams.get("mode")||"themes");
  const folderId=sanitizeId(url.searchParams.get("folderId"))||rootFolderId;
  const theme=cleanLabel(url.searchParams.get("theme")||"");
  const rawSearch=String(url.searchParams.get("q")||url.searchParams.get("code")||url.searchParams.get("imageId")||"").trim();
  const searchCode=rawSearch.replace(/\D/g,"").slice(0,20);
  const searchImageId=sanitizeId(url.searchParams.get("imageId")||rawSearch);
  if(mode==="themes"){
   const folders=(await listChildren(folderId,apiKey)).filter(f=>f.mimeType===FOLDER_MIME).map(f=>applyFolderRule({id:f.id,name:cleanLabel(f.name),rawName:f.name,kind:"theme"},config,"theme")).filter(f=>!f.hidden); sortFolders(folders);
   return json({ok:true,mode,folders,configVersion:config.ui&&config.ui.cacheVersion||config.version||1},200,15);
  }
  if(mode==="products"){
   const children=await listChildren(folderId,apiKey);
   const folders=children.filter(f=>f.mimeType===FOLDER_MIME).map(f=>applyFolderRule({id:f.id,name:cleanLabel(f.name),rawName:f.name,kind:"folder",product:"",productName:"",label:cleanLabel(f.name)},config,"subtheme")).filter(f=>!f.hidden); sortFolders(folders);
   if(children.some(f=>String(f.mimeType||"").startsWith("image/")))folders.push(makeBolinhasProduct(folderId,bolinhas));
   return json({ok:true,mode,theme,folders},200,15);
  }
  if(mode==="items"){
   const items=(await listChildren(folderId,apiKey)).filter(f=>String(f.mimeType||"").startsWith("image/")).map(f=>itemFromFile(f,{folderId,theme,bolinhas,config})).filter(i=>i.code&&!isBlockedArt(i.code,config)&&!isHiddenTheme(i.theme,config)).sort((a,b)=>(Number(b.sortId)||0)-(Number(a.sortId)||0));
   return json({ok:true,mode,theme:displayTheme(theme,config),product:bolinhas.productKey,productName:bolinhas.label,total:items.length,items},200,15);
  }
  if(mode==="search"){
   if((!searchCode||searchCode.length<2)&&!searchImageId)return json({ok:true,mode,items:[]},200,15);
   const items=await searchImages(rawSearch,searchCode,searchImageId,apiKey,rootFolderId,bolinhas,config);
   return json({ok:true,mode,total:items.length,items},200,15);
  }
  if(mode==="folderSearch"){
   const q=cleanLabel(url.searchParams.get("q")||""); if(!q||normalizeText(q).length<2)return json({ok:true,mode,results:[]},200,15);
   const results=await searchFolders(q,apiKey,rootFolderId,config); return json({ok:true,mode,total:results.length,results},200,15);
  }
  return json({ok:false,error:"MODO_INVALIDO"},400);
 }catch(error){return json({ok:false,error:"FALHA_AO_LER_DRIVE",detail:String(error&&error.message||error)},500)}
}
function makeBolinhasProduct(folderId,bolinhas){return{id:folderId,name:bolinhas.label,rawName:bolinhas.label,kind:"product",product:bolinhas.productKey,productName:bolinhas.label,label:bolinhas.label,unitPrice:bolinhas.unitPrice,price:bolinhas.unitPrice,priceLabel:bolinhas.priceLabel,minQty:bolinhas.minQty,step:bolinhas.step,directItems:true,skipProductsStep:bolinhas.skipProductsStep,disableCustomization:bolinhas.disableCustomization,customizationDisabled:bolinhas.disableCustomization,allowCustomSize:!bolinhas.disableCustomization,canCustomize:!bolinhas.disableCustomization}}
async function listChildren(folderId,apiKey){const out=[];let pageToken="";do{const p=new URLSearchParams({key:apiKey,q:`'${folderId}' in parents and trashed = false`,fields:"nextPageToken, files(id,name,mimeType,webViewLink,modifiedTime,parents)",pageSize:"1000",orderBy:"folder,name_natural",supportsAllDrives:"true",includeItemsFromAllDrives:"true"});if(pageToken)p.set("pageToken",pageToken);const r=await fetch(`${DRIVE_API}?${p.toString()}`,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Drive API ${r.status}`);const d=await r.json();out.push(...(d.files||[]));pageToken=d.nextPageToken||""}while(pageToken);return out}
async function searchFolders(query,apiKey,rootFolderId,config){const q=String(query||"").replace(/'/g,"\\'").trim();let out=[];try{const p=new URLSearchParams({key:apiKey,q:`name contains '${q}' and trashed = false and mimeType = '${FOLDER_MIME}'`,fields:"files(id,name,mimeType,parents)",pageSize:"40",orderBy:"name_natural",supportsAllDrives:"true",includeItemsFromAllDrives:"true"});const r=await fetch(`${DRIVE_API}?${p.toString()}`,{headers:{Accept:"application/json"}});if(r.ok){const d=await r.json();out=await foldersFromFiles(d.files||[],apiKey,rootFolderId,config)}}catch(_){}if(out.length<12){const deep=await deepSearch(rootFolderId,apiKey,config,{folderQuery:query,maxFolders:30,maxImages:0});for(const item of deep.folders){if(!out.some(x=>x.id===item.id))out.push(item)}}return out.slice(0,30).sort((a,b)=>a.path.localeCompare(b.path,"pt-BR",{numeric:true}))}
async function foldersFromFiles(files,apiKey,rootFolderId,config){const out=[];for(const f of files){try{if(isHiddenTheme(f.name,config))continue;const ancestry=await buildAncestry(f.id,apiKey);const rootIndex=ancestry.findIndex(a=>a.id===rootFolderId);if(rootIndex===-1)continue;const belowRoot=ancestry.slice(rootIndex+1);if(!belowRoot.length)continue;const themeFolder=belowRoot[0];if(isHiddenTheme(themeFolder.name,config))continue;out.push(folderResult(f,belowRoot,config))}catch(_){}if(out.length>=30)break}return out}
function folderResult(f,belowRoot,config){const themeFolder=belowRoot[0]||f;return{id:f.id,name:displayTheme(f.name,config),rawName:f.name,label:displayTheme(f.name,config),kind:"folder",product:"",productName:"",theme:displayTheme(themeFolder.name,config),themeId:themeFolder.id,trail:belowRoot.slice(1,Math.max(1,belowRoot.length-1)).filter(x=>!isHiddenTheme(x.name,config)).map(x=>({id:x.id,name:displayTheme(x.name,config),kind:"folder"})),path:belowRoot.map(x=>displayTheme(x.name,config)).join(" / ")}}
async function searchImages(raw,codeValue,imageId,apiKey,rootFolderId,bolinhas,config){const out=[];if(imageId){const byId=await searchByImageId(imageId,apiKey,rootFolderId,bolinhas,config);out.push(...byId)}if(codeValue&&codeValue.length>=2&&!isBlockedArt(codeValue,config)){const byCode=await searchByCode(codeValue,apiKey,rootFolderId,bolinhas,config);for(const item of byCode){if(!out.some(x=>x.id===item.id))out.push(item)}}if(out.length<12){const deep=await deepSearch(rootFolderId,apiKey,config,{codeQuery:codeValue,imageId:imageId,maxFolders:0,maxImages:24});for(const item of deep.images.map(x=>itemFromFile(x.file,{folderId:x.parentId,theme:x.themeLabel,bolinhas,config}))){if(!out.some(x=>x.id===item.id))out.push(item)}}return out.slice(0,24)}
async function deepSearch(rootFolderId,apiKey,config,opts){const folderQuery=normalizeText(opts.folderQuery||""),codeQuery=String(opts.codeQuery||"").replace(/\D/g,""),imageId=sanitizeId(opts.imageId||""),maxFolders=opts.maxFolders||0,maxImages=opts.maxImages||0,out={folders:[],images:[]};async function walk(folderId,path,depth){if(depth>7)return;const children=await listChildren(folderId,apiKey);for(const f of children){if(f.mimeType===FOLDER_MIME){if(!isHiddenTheme(f.name,config)){const nextPath=path.concat([f]);const text=normalizeText(nextPath.map(x=>x.name).join(" / "));if(maxFolders&&folderQuery&&text.includes(folderQuery)&&!out.folders.some(x=>x.id===f.id))out.folders.push(folderResult(f,nextPath,config));if(out.folders.length<maxFolders||out.images.length<maxImages)await walk(f.id,nextPath,depth+1)}}else if(String(f.mimeType||"").startsWith("image/")){if(!maxImages)continue;const parsed=parseArtFilename(f.name),artCode=parsed.code||"";const matchId=imageId&&f.id===imageId;const matchCode=codeQuery&&artCode&&artCode.includes(codeQuery);if((matchId||matchCode)&&!isBlockedArt(artCode,config)){const themeLabel=parsed.theme||path.map(x=>cleanLabel(x.name)).join(" / ")||"Sem tema";if(!isHiddenTheme(themeLabel,config)&&!path.some(x=>isHiddenTheme(x.name,config))&&!out.images.some(x=>x.file.id===f.id))out.images.push({file:f,parentId:folderId,themeLabel})}}if(out.folders.length>=maxFolders&&out.images.length>=maxImages)return}}await walk(rootFolderId,[],0);return out}
async function searchByImageId(fileId,apiKey,rootFolderId,bolinhas,config){const id=sanitizeId(fileId);if(!id)return[];let f;try{f=await getImageFile(id,apiKey)}catch(_){return[]}if(!String(f.mimeType||"").startsWith("image/"))return[];const parsed=parseArtFilename(f.name),artCode=parsed.code;if(artCode&&isBlockedArt(artCode,config))return[];const parentId=f.parents&&f.parents[0]||"";const ancestry=await buildAncestry(parentId,apiKey);const rootIndex=ancestry.findIndex(a=>a.id===rootFolderId);if(rootIndex===-1)return[];const belowRoot=ancestry.slice(rootIndex+1);if(!belowRoot.length)return[];const themeLabel=parsed.theme||belowRoot.map(x=>cleanLabel(x.name)).join(" / ")||"Sem tema";if(isHiddenTheme(themeLabel,config)||belowRoot.some(x=>isHiddenTheme(x.name,config)))return[];return[itemFromFile(f,{folderId:parentId,theme:themeLabel,bolinhas,config})]}
async function searchByCode(code,apiKey,rootFolderId,bolinhas,config){const safe=String(code||"").replace(/[^0-9]/g,"");if(!safe||safe.length<2||isBlockedArt(safe,config))return[];const p=new URLSearchParams({key:apiKey,q:`name contains '${safe}' and trashed = false and mimeType contains 'image/'`,fields:"files(id,name,mimeType,webViewLink,parents)",pageSize:"40",orderBy:"name_natural",supportsAllDrives:"true",includeItemsFromAllDrives:"true"});const r=await fetch(`${DRIVE_API}?${p.toString()}`,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Drive API ${r.status}`);const d=await r.json(),out=[];for(const f of(d.files||[])){const parsed=parseArtFilename(f.name),artCode=parsed.code;if(!artCode||!artCode.includes(safe)||isBlockedArt(artCode,config))continue;const parentId=f.parents&&f.parents[0]||"";const ancestry=await buildAncestry(parentId,apiKey);const rootIndex=ancestry.findIndex(a=>a.id===rootFolderId);if(rootIndex===-1)continue;const belowRoot=ancestry.slice(rootIndex+1);if(!belowRoot.length)continue;const themeLabel=parsed.theme||belowRoot.map(x=>cleanLabel(x.name)).join(" / ")||"Sem tema";if(isHiddenTheme(themeLabel,config)||belowRoot.some(x=>isHiddenTheme(x.name,config)))continue;out.push(itemFromFile(f,{folderId:parentId,theme:themeLabel,bolinhas,config}));if(out.length>=24)break}return out.sort((a,b)=>(Number(b.sortId)||0)-(Number(a.sortId)||0))}
function itemFromFile(file,{folderId,theme,bolinhas,config}){const parsed=parseArtFilename(file.name);const image=`https://drive.google.com/thumbnail?id=${encodeURIComponent(file.id)}&sz=w1200`;return{id:file.id,code:parsed.code,sortId:Number(parsed.code)||0,theme:displayTheme(parsed.theme||theme||"Sem tema",config),product:bolinhas.productKey,productName:bolinhas.label,productLabel:bolinhas.label,size:parsed.dimension||"50x50",dimension:parsed.dimension||"50x50",embeddedTheme:parsed.theme,embeddedProduct:parsed.productRaw,originalName:file.name,themeId:"",productFolderId:folderId,image,thumbnail:image,driveUrl:file.webViewLink||`https://drive.google.com/file/d/${file.id}/view`,unitPrice:bolinhas.unitPrice,price:bolinhas.unitPrice,priceLabel:bolinhas.priceLabel,minQty:bolinhas.minQty,step:bolinhas.step,disableCustomization:bolinhas.disableCustomization,customizationDisabled:bolinhas.disableCustomization,allowCustomSize:!bolinhas.disableCustomization,canCustomize:!bolinhas.disableCustomization,measureDisabled:bolinhas.disableCustomization}}
function parseArtFilename(value){const base=String(value||"").replace(/\.[^.]+$/,"").trim();const parts=base.split("_").map(p=>p.trim()).filter(Boolean);const leadingId=base.match(/^\s*(\d{1,20})(?:[_\-\s]|$)/);const code=leadingId?leadingId[1]:cleanCode(base);return{code,theme:cleanLabel(parts[1]||""),productRaw:cleanLabel(parts[2]||""),dimension:normalizeDimension(parts.slice(3).join(" "))}}
async function buildAncestry(startFolderId,apiKey){const ancestry=[];let currentId=startFolderId;const seen=new Set();for(let depth=0;depth<12&&currentId&&!seen.has(currentId);depth++){seen.add(currentId);const file=await getFile(currentId,apiKey);ancestry.unshift(file);currentId=file.parents&&file.parents[0]}return ancestry}
async function getFile(fileId,apiKey){const p=new URLSearchParams({key:apiKey,fields:"id,name,mimeType,parents",supportsAllDrives:"true"});const r=await fetch(`${DRIVE_API}/${encodeURIComponent(fileId)}?${p.toString()}`,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Drive file ${r.status}`);return r.json()}
async function getImageFile(fileId,apiKey){const p=new URLSearchParams({key:apiKey,fields:"id,name,mimeType,parents,webViewLink",supportsAllDrives:"true"});const r=await fetch(`${DRIVE_API}/${encodeURIComponent(fileId)}?${p.toString()}`,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Drive file ${r.status}`);return r.json()}
function cleanCode(value){const base=String(value||"").replace(/\.[^.]+$/,"").trim();const leadingId=base.match(/^\s*(\d{1,20})(?:[_\-\s]|$)/);if(leadingId)return leadingId[1];const arteMatch=base.match(/(?:arte|art)[^\d]*(\d+)/i);if(arteMatch)return arteMatch[1];const nums=base.match(/\d+/g);return nums?nums[0]:base.replace(/[^\w-]/g,"").toUpperCase()}
function normalizeDimension(value){const text=String(value||"").trim();if(!text)return"";const compact=text.replace(/\s+/g,"").replace(/×/g,"x").toLowerCase();const sizeMatch=compact.match(/(\d+(?:[\.,]\d+)?)[xX](\d+(?:[\.,]\d+)?)/);if(sizeMatch)return`${sizeMatch[1]}x${sizeMatch[2]}`.replace(/,/g,".");return cleanLabel(text)}
function sanitizeId(value){const id=String(value||"").trim();return/^[A-Za-z0-9_-]{10,}$/.test(id)?id:""}
function json(payload,status=200,cache=0){return new Response(JSON.stringify(payload),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":cache?`public, max-age=${cache}, s-maxage=${cache}`:"no-store, max-age=0","X-Content-Type-Options":"nosniff"}})}